// ═══════════════════════════════════════════════════════════════
//  OXYTOOLS — État de l'application (données uniquement, pas de logique)
// ═══════════════════════════════════════════════════════════════

use eframe::egui;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use crate::modules;

#[cfg(feature = "api")]
#[derive(Clone)]
pub struct ScrapeEntry {
    pub(crate) data: modules::scrap::ScrapeResult,
    pub(crate) texture: Option<egui::TextureHandle>,
}

#[derive(PartialEq, Clone, Copy, Debug)]
pub enum ModuleType {
    Archive,
    #[cfg(feature = "api")]
    Audio,
    Doc,
    Image,
    #[cfg(feature = "api")]
    Scrapper,
    #[cfg(feature = "api")]
    Tag,
    #[cfg(feature = "api")]
    Video,
    Rename,
    Settings,
}

pub struct OxytoolsApp {
    #[cfg(feature = "api")]
    pub(crate) copie_flux: bool,
    pub(crate) current_files: Vec<PathBuf>,
    pub(crate) current_stem: String,
    pub(crate) format_choisi: String,
        pub(crate) module_actif: ModuleType,
        pub(crate) process: Option<std::process::Child>,
        pub(crate) ratio_img: u32,
        #[cfg(feature = "api")]
        pub(crate) results_ui: Arc<Mutex<Vec<ScrapeEntry>>>,
        pub(crate) status: Arc<Mutex<String>>,
        pub(crate) deps_manquantes: Vec<String>,
        #[cfg(feature = "api")]
        pub(crate) audio_action: String,
        #[cfg(feature = "api")]
        pub(crate) audio_formats_dispo: Vec<String>,
        #[cfg(feature = "api")]
        pub(crate) tag_edit_val: String,
        pub(crate) use_custom_nfo: bool,
        pub(crate) custom_nfo_path: Option<std::path::PathBuf>,
        pub(crate) use_custom_poster: bool,
        pub(crate) custom_poster_path: Option<std::path::PathBuf>,
        pub(crate) current_theme: String,
        pub(crate) custom_config_dir: Option<std::path::PathBuf>,
        pub(crate) lang: &'static crate::lang::Lang,
        pub(crate) lang_id: &'static str,
        pub(crate) rename_cfg: modules::rename::RenameConfig,
        pub(crate) rename_previews: Vec<(std::path::PathBuf, String)>,
        pub(crate) rename_results: Vec<modules::rename::RenameResult>,
        pub(crate) rename_multi_find: String,
        pub(crate) rename_multi_replace: String,
        pub(crate) rename_ant_sets: Vec<String>,
        pub(crate) rename_ant_path: Option<PathBuf>,
        pub(crate) rename_undo_stack: Vec<Vec<modules::rename::RenameResult>>,
        pub(crate) rename_last_list_path: Option<PathBuf>,
        pub(crate) tmdb_api_key: String,
        pub(crate) fanart_api_key: String,
        pub(crate) keys_env_path: Option<PathBuf>,
        pub(crate) scrap_status: String,
        pub(crate) fetch_fanart: bool,
        pub(crate) fetch_clearlogo: bool,
        pub(crate) scrap_manual_search_enabled: bool,
        pub(crate) scrap_fullscreen: Option<egui::TextureHandle>,
        pub(crate) scrap_popup_query: Option<String>,
        pub(crate) no_result_flag: Arc<Mutex<bool>>,
        pub(crate) scrap_last_is_series: bool,
        pub(crate) save_doc_format: bool,
        pub(crate) save_image_format: bool,
        pub(crate) save_archive_format: bool,
        pub(crate) archive_niveau: u32,
        pub(crate) archive_action: String,
        pub(crate) archive_backup_source: String,
        pub(crate) archive_backup_dest: String,
        pub(crate) archive_backup_exclusions: String,
        pub(crate) archive_multi_source: String,
        #[cfg(feature = "api")]
        pub(crate) save_audio_format: bool,
        #[cfg(feature = "api")]
        pub(crate) audio_qualite: u32,
        #[cfg(feature = "api")]
        pub(crate) save_video_format: bool,
        #[cfg(feature = "api")]
        pub(crate) video_speed: u32,
        pub(crate) image_action: String,
        pub(crate) jxl_mode: String,
        pub(crate) rotation_angle: u32,
        pub(crate) crop_x: u32,
        pub(crate) crop_y: u32,
        pub(crate) crop_width: u32,
        pub(crate) crop_height: u32,
        pub(crate) resize_width: String,
        pub(crate) resize_height: String,
        pub(crate) resize_max_kb: String,
        pub(crate) doc_action: String,
        pub(crate) pdf_rotation_angle: u16,
        pub(crate) pdf_pages_spec: String,
        pub(crate) pdf_crop_x: f64,
        pub(crate) pdf_crop_y: f64,
        pub(crate) pdf_crop_w: f64,
        pub(crate) pdf_crop_h: f64,
        pub(crate) pdf_num_debut: u32,
        pub(crate) pdf_compress_niveau: u32,
        pub(crate) pdf_num_position: String,
        pub(crate) pdf_num_taille: f64,
        pub(crate) pdf_owner_pass: String,
        pub(crate) pdf_user_pass: String,
        pub(crate) pdf_allow_print: bool,
        pub(crate) pdf_allow_copy: bool,
        pub(crate) pdf_unlock_pass: String,
        pub(crate) pdf_wm_texte: String,
        pub(crate) pdf_wm_taille: f64,
        pub(crate) pdf_wm_opacite: f64,
        pub(crate) pdf_nouvel_ordre: String,
        pub(crate) pdf_annot_texte: String,
        pub(crate) pdf_annot_x: f64,
        pub(crate) pdf_annot_y: f64,
        pub(crate) pdf_annot_w: f64,
        pub(crate) pdf_annot_h: f64,
        pub(crate) pdf_sign_nom: String,
        pub(crate) pdf_sign_position: String,
        pub(crate) pdf_sign_taille: f64,
        pub(crate) img_wm_texte: String,
        pub(crate) img_wm_taille: f32,
        pub(crate) img_wm_opacite: f32,
        pub(crate) img_meme_top: String,
        pub(crate) img_meme_bottom: String,
        pub(crate) img_upscale_factor: u32,
        pub(crate) ico_size_16: bool,
        pub(crate) ico_size_32: bool,
        pub(crate) ico_size_64: bool,
        pub(crate) ico_size_128: bool,
        pub(crate) ico_size_256: bool,
        pub(crate) ico_size_512: bool,
        pub(crate) ico_size_custom: bool,
        pub(crate) ico_custom_w: String,
        pub(crate) ico_custom_h: String,
        pub(crate) max_parallel_jobs: usize,
        pub(crate) active_jobs: Arc<Mutex<usize>>,
        pub(crate) completed_jobs: Arc<Mutex<usize>>,
        pub(crate) total_jobs: Arc<Mutex<usize>>,
        pub(crate) job_queue: Arc<Mutex<Vec<PathBuf>>>,
        pub(crate) conv_progress: Arc<Mutex<f32>>,
        pub(crate) active_pids: Arc<Mutex<Vec<u32>>>,
}
impl Default for OxytoolsApp {
    fn default() -> Self {
        Self {
            #[cfg(feature = "api")]
            copie_flux: false,
            current_files: Vec::new(),
            current_stem: String::new(),
            format_choisi: "mp4".into(),
                module_actif: ModuleType::Image,
                process: None,
                ratio_img: 2,
                #[cfg(feature = "api")]
                results_ui: Arc::new(Mutex::new(Vec::new())),
                status: Arc::new(Mutex::new(crate::lang::EN.drop_files.into())),
                deps_manquantes: Vec::new(),
                #[cfg(feature = "api")]
                audio_action: "Convert".into(),
                #[cfg(feature = "api")]
                audio_formats_dispo: vec!["aac","flac","m4a","mp3","ogg","opus","wav"].into_iter().map(String::from).collect(),
                #[cfg(feature = "api")]
                tag_edit_val: String::new(),
                use_custom_nfo: false,
                custom_nfo_path: None,
                use_custom_poster: false,
                custom_poster_path: None,
                current_theme: "Dark".into(),
                custom_config_dir: None,
                tmdb_api_key: String::new(),
                fanart_api_key: String::new(),
                keys_env_path: None,
                scrap_status: String::new(),
                fetch_fanart: false,
                fetch_clearlogo: false,
                scrap_manual_search_enabled: false,
                scrap_fullscreen: None,
                scrap_popup_query: None,
                no_result_flag: Arc::new(Mutex::new(false)),
                scrap_last_is_series: false,
                save_doc_format: false,
                save_image_format: false,
                save_archive_format: false,
                archive_niveau: 6,
                archive_action: "compress".into(),
                archive_backup_source: String::new(),
                archive_backup_dest: String::new(),
                archive_backup_exclusions: ".git, .github, target".into(),
                archive_multi_source: String::new(),
                #[cfg(feature = "api")]
                save_audio_format: false,
                #[cfg(feature = "api")]
                audio_qualite: 2,
                #[cfg(feature = "api")]
                save_video_format: false,
                #[cfg(feature = "api")]
                video_speed: 4,
                image_action: "Convert".into(),
                jxl_mode: "lossless".into(),
                rotation_angle: 90,
                crop_x: 0,
                crop_y: 0,
                crop_width: 100,
                crop_height: 100,
                resize_width: String::new(),
                resize_height: String::new(),
                resize_max_kb: String::new(),
                doc_action: "Convert".into(),
                pdf_rotation_angle: 90,
                pdf_pages_spec: "1-end".into(),
                pdf_crop_x: 0.0,
                pdf_crop_y: 0.0,
                pdf_crop_w: 100.0,
                pdf_crop_h: 100.0,
                pdf_num_debut: 1,
                pdf_compress_niveau: 9,
                pdf_num_position: "BasCentre".into(),
                pdf_num_taille: 10.0,
                pdf_owner_pass: String::new(),
                pdf_user_pass: String::new(),
                pdf_allow_print: true,
                pdf_allow_copy: true,
                pdf_unlock_pass: String::new(),
                pdf_wm_texte: "CONFIDENTIEL".into(),
                pdf_wm_taille: 60.0,
                pdf_wm_opacite: 0.35,
                pdf_nouvel_ordre: String::new(),
                pdf_annot_texte: String::new(),
                pdf_annot_x: 10.0,
                pdf_annot_y: 80.0,
                pdf_annot_w: 30.0,
                pdf_annot_h: 10.0,
                pdf_sign_nom: String::new(),
                pdf_sign_position: "BasDroite".into(),
                pdf_sign_taille: 10.0,
                img_wm_texte: "WATERMARK".into(),
                img_wm_taille: 48.0,
                img_wm_opacite: 0.3,
                img_meme_top: String::new(),
                img_meme_bottom: String::new(),
                img_upscale_factor: 2,
                ico_size_16: false,
                ico_size_32: false,
                ico_size_64: false,
                ico_size_128: false,
                ico_size_256: true,
                ico_size_512: false,
                ico_size_custom: false,
                ico_custom_w: String::new(),
                ico_custom_h: String::new(),
                max_parallel_jobs: 4,
                active_jobs: Arc::new(Mutex::new(0)),
                completed_jobs: Arc::new(Mutex::new(0)),
                total_jobs: Arc::new(Mutex::new(0)),
                job_queue: Arc::new(Mutex::new(Vec::new())),
                conv_progress: Arc::new(Mutex::new(-1.0f32)),
                active_pids: Arc::new(Mutex::new(Vec::new())),
                rename_cfg: modules::rename::RenameConfig::default(),
                rename_previews: Vec::new(),
                rename_results: Vec::new(),
                rename_multi_find: String::new(),
                rename_multi_replace: String::new(),
                rename_ant_sets: Vec::new(),
                rename_ant_path: None,
                rename_undo_stack: Vec::new(),
                rename_last_list_path: None,
                lang: &crate::lang::EN,
                lang_id: "en",
        }
    }
}
