#![allow(dead_code)]

pub struct Lang {
    // Status bar
    pub drop_files: &'static str,
    pub starting_tasks: &'static str,       // format: {}
    pub processing_files: &'static str,     // format: {}/{}
    pub done_files: &'static str,           // format: {}/{}
    pub files_loaded: &'static str,         // format: {}
    pub done: &'static str,
    pub missing: &'static str,              // format: {}
    pub active_pending: &'static str,       // format: {} · {}
    pub done_processed: &'static str,       // format: {}
    pub processing_pct: &'static str,       // format: {}/{} ({}%)

    // Modules tabs
    pub tab_archive: &'static str,
    pub tab_audio: &'static str,
    pub tab_doc: &'static str,
    pub tab_image: &'static str,
    pub tab_scrapper: &'static str,
    pub tab_tag: &'static str,
    pub tab_tools: &'static str,
    pub tab_video: &'static str,
    pub tab_settings: &'static str,

    // Common
    pub format_label: &'static str,
    pub action_label: &'static str,
    pub angle_label: &'static str,
    pub pages_label: &'static str,
    pub pages_hint: &'static str,
    pub save_format: &'static str,
    pub run_all: &'static str,
    pub browse: &'static str,
    pub clear_all: &'static str,
    pub drop_here: &'static str,

    // Archive
    pub compression_slider: &'static str,

    // Doc actions
    pub doc_convert: &'static str,
    pub doc_pdf_compress: &'static str,
    pub doc_pdf_crop: &'static str,
    pub doc_pdf_delete_pages: &'static str,
    pub doc_pdf_merge: &'static str,
    pub doc_pdf_number_pages: &'static str,
    pub doc_pdf_organize: &'static str,
    pub doc_pdf_protect: &'static str,
    pub doc_pdf_repair: &'static str,
    pub doc_pdf_rotate: &'static str,
    pub doc_pdf_split: &'static str,
    pub doc_pdf_unlock: &'static str,
    pub doc_pdf_watermark: &'static str,
    // Doc hints
    pub doc_split_hint1: &'static str,
    pub doc_split_hint2: &'static str,
    pub doc_merge_hint1: &'static str,
    pub doc_merge_hint2: &'static str,
    pub doc_compress_hint: &'static str,
    pub doc_repair_hint1: &'static str,
    pub doc_repair_hint2: &'static str,
    pub doc_repair_hint3: &'static str,
    pub doc_watermark_hint1: &'static str,
    pub doc_watermark_hint2: &'static str,
    pub doc_margins: &'static str,
    pub doc_new_order: &'static str,
    pub doc_delete_pages: &'static str,
    pub doc_start: &'static str,
    pub doc_position: &'static str,
    pub doc_size: &'static str,
    pub doc_owner_password: &'static str,
    pub doc_user_password: &'static str,
    pub doc_password: &'static str,
    pub doc_allow_print: &'static str,
    pub doc_allow_copy: &'static str,
    pub doc_text: &'static str,
    pub doc_opacity: &'static str,

    // Image actions
    pub img_convert: &'static str,
    pub img_crop: &'static str,
    pub img_resize: &'static str,
    pub img_rotate: &'static str,
    pub img_quality_slider: &'static str,
    pub img_resize_px: &'static str,
    pub img_width: &'static str,
    pub img_height: &'static str,
    pub img_andor: &'static str,
    pub img_max_size: &'static str,
    pub img_coordinates: &'static str,

    // Audio
    pub audio_extract: &'static str,
    pub audio_convert: &'static str,
    pub audio_detect_codec: &'static str,
    pub audio_vbr_slider: &'static str,
    pub audio_extract_hint1: &'static str,
    pub audio_extract_hint2: &'static str,

    // Video
    pub video_stream_copy: &'static str,
    pub video_quality_slider: &'static str,

    // Scrapper
    pub scrap_tmdb_key: &'static str,
    pub scrap_fanart_key: &'static str,
    pub scrap_save_keys: &'static str,
    pub scrap_movie: &'static str,
    pub scrap_series: &'static str,
    pub scrap_choose: &'static str,

    // Tag
    pub tag_mark_watched: &'static str,
    pub tag_inject_nfo: &'static str,
    pub tag_add_poster: &'static str,
    pub tag_reset_tags: &'static str,
    pub tag_edit_title: &'static str,

    // Rename
    pub tab_rename: &'static str,
    pub rename_find_replace: &'static str,
    pub rename_find: &'static str,
    pub rename_replace_with: &'static str,
    pub rename_insert: &'static str,
    pub rename_text: &'static str,
    pub rename_at_pos: &'static str,
    pub rename_delete_range: &'static str,
    pub rename_enable: &'static str,
    pub rename_from: &'static str,
    pub rename_count: &'static str,
    pub rename_numbering: &'static str,
    pub rename_start: &'static str,
    pub rename_step: &'static str,
    pub rename_padding: &'static str,
    pub rename_separator: &'static str,
    pub rename_position: &'static str,
    pub rename_prefix: &'static str,
    pub rename_suffix: &'static str,
    pub rename_case: &'static str,
    pub rename_clean: &'static str,
    pub rename_trim_spaces: &'static str,
    pub rename_double_spaces: &'static str,
    pub rename_leading_dots: &'static str,
    pub rename_strip_chars: &'static str,
    pub rename_extension: &'static str,
    pub rename_new_ext: &'static str,
    pub rename_reset: &'static str,
    pub rename_original: &'static str,
    pub rename_new_name: &'static str,
    pub rename_apply: &'static str,
    pub rename_done: &'static str,

    // Settings
    pub settings_heading: &'static str,
    pub settings_theme: &'static str,
    pub settings_performance: &'static str,
    pub settings_max_jobs: &'static str,
    pub settings_jobs_hint: &'static str,
}

pub const EN: Lang = Lang {
    drop_files: "Drop files here",
    starting_tasks: "🚀 Starting {} tasks...",
    processing_files: "⚙️ Processing {}/{} files...",
    done_files: "✅ Done: {}/{} files",
    files_loaded: "📁 {} files loaded",
    done: "✅ Done",
    missing: "⚠️ Missing: {}",
    active_pending: "{} active · {} pending",
    done_processed: "✅ Done - {} files processed",
    processing_pct: "⚙️ {}/{} files ({}%)",

    tab_archive: "📦 Archive",
    tab_audio: "🎵 Audio",
    tab_doc: "📄 Doc",
    tab_image: "🖼️ Picture",
    tab_scrapper: "🔍 Scrapper",
    tab_tag: "🏷️ Tag",
    tab_tools: "🛠 Tools",
    tab_video: "🎬 Video",
    tab_settings: "⚙ Settings",

    format_label: "Format:",
    action_label: "Action:",
    angle_label: "Angle:",
    pages_label: "Pages:",
    pages_hint: "(e.g. 1,3,5 or empty = all)",
    save_format: "💾 Save format",
    run_all: "🔥 RUN ALL",
    browse: "📂 Browse",
    clear_all: "🗑️ Clear all",
    drop_here: "📥 Drop your files here",

    compression_slider: "Compression (1=fast, 9=quality)",

    doc_convert: "Convert",
    doc_pdf_compress: "PDF compress",
    doc_pdf_crop: "PDF crop",
    doc_pdf_delete_pages: "PDF delete pages",
    doc_pdf_merge: "PDF merge",
    doc_pdf_number_pages: "PDF number pages",
    doc_pdf_organize: "PDF organize pages",
    doc_pdf_protect: "PDF protect",
    doc_pdf_repair: "PDF repair",
    doc_pdf_rotate: "PDF rotate",
    doc_pdf_split: "PDF split",
    doc_pdf_unlock: "PDF unlock",
    doc_pdf_watermark: "PDF watermark",
    doc_split_hint1: "✂️ Splits each PDF page into a separate file",
    doc_split_hint2: "💡 Creates a _pages/ folder next to the source file",
    doc_merge_hint1: "📎 Merges all loaded files into a single PDF",
    doc_merge_hint2: "💡 Output will be merged_oxytools.pdf",
    doc_compress_hint: "🗜️ Reduces PDF size by recompressing",
    doc_repair_hint1: "🔧 Attempts to repair a corrupted document",
    doc_repair_hint2: "Removes orphan objects, recompresses, renumbers",
    doc_repair_hint3: "💡 Works on all Doc module formats",
    doc_watermark_hint1: "💧 Adds a diagonal text watermark",
    doc_watermark_hint2: "💡 Works on all Doc module formats",
    doc_margins: "Margins in % (0.0 - 100.0):",
    doc_new_order: "🔀 New page order (e.g. 3,1,2):",
    doc_delete_pages: "🗑️ Pages to delete (e.g. 2,4,6):",
    doc_start: "Start:",
    doc_position: "Position:",
    doc_size: "Size:",
    doc_owner_password: "Owner password:",
    doc_user_password: "User password:",
    doc_password: "Password:",
    doc_allow_print: "Allow printing",
    doc_allow_copy: "Allow copying",
    doc_text: "Text:",
    doc_opacity: "Opacity:",

    img_convert: "Convert",
    img_crop: "Crop",
    img_resize: "Resize",
    img_rotate: "Rotate",
    img_quality_slider: "Quality (1=fast, 10=quality)",
    img_resize_px: "Resize by pixels:",
    img_width: "Width:",
    img_height: "Height:",
    img_andor: "AND/OR",
    img_max_size: "Max size (KB):",
    img_coordinates: "Coordinates in % (0-100):",

    audio_extract: "Audio extract",
    audio_convert: "Convert",
    audio_detect_codec: "🔍 Detect codec",
    audio_vbr_slider: "VBR (1=fast, 9=quality)",
    audio_extract_hint1: "🎵 Extracts audio from a video (direct copy, no re-encoding)",
    audio_extract_hint2: "💡 Output format is detected automatically",

    video_stream_copy: "Stream copy",
    video_quality_slider: "Quality (1=fast, 8=quality)",

    scrap_tmdb_key: "TMDB API Key:",
    scrap_fanart_key: "Fanart API Key:",
    scrap_save_keys: "💾 Save keys",
    scrap_movie: "🎬 Movie",
    scrap_series: "📺 Series",
    scrap_choose: "Choose",

    tag_mark_watched: "✅ Mark as WATCHED",
    tag_inject_nfo: "📥 Inject tags from NFO",
    tag_add_poster: "🖼️ Add poster / fanart",
    tag_reset_tags: "🗑️ Reset Tags",
    tag_edit_title: "✏️ Edit Title",

    tab_rename: "✏️ Rename",
    rename_find_replace: "🔍 Find & Replace",
    rename_find: "Find:",
    rename_replace_with: "Replace:",
    rename_insert: "➕ Insert",
    rename_text: "Text:",
    rename_at_pos: "At position:",
    rename_delete_range: "✂️ Delete range",
    rename_enable: "Enable",
    rename_from: "From:",
    rename_count: "Count:",
    rename_numbering: "🔢 Numbering",
    rename_start: "Start:",
    rename_step: "Step:",
    rename_padding: "Padding:",
    rename_separator: "Separator:",
    rename_position: "Position:",
    rename_prefix: "Prefix",
    rename_suffix: "Suffix",
    rename_case: "🔤 Case",
    rename_clean: "🧹 Clean",
    rename_trim_spaces: "Trim spaces",
    rename_double_spaces: "Remove double spaces",
    rename_leading_dots: "Remove leading dots",
    rename_strip_chars: "Strip chars:",
    rename_extension: "📎 Extension",
    rename_new_ext: "New ext:",
    rename_reset: "↺ Reset",
    rename_original: "Original",
    rename_new_name: "→ New name",
    rename_apply: "🔥 Apply rename",
    rename_done: "files renamed",

    settings_heading: "Settings",
    settings_theme: "Theme:",
    settings_performance: "Performance",
    settings_max_jobs: "Max parallel jobs:",
    settings_jobs_hint: "💡 Higher = faster but more CPU load",
};

pub const FR: Lang = Lang {
    drop_files: "Déposez des fichiers",
    starting_tasks: "🚀 Démarrage de {} tâches...",
    processing_files: "⚙️ Traitement {}/{} fichiers...",
    done_files: "✅ Terminé : {}/{} fichiers",
    files_loaded: "📁 {} fichiers chargés",
    done: "✅ Terminé",
    missing: "⚠️ Manquant : {}",
    active_pending: "{} actifs · {} en attente",
    done_processed: "✅ Terminé — {} fichiers traités",
    processing_pct: "⚙️ {}/{} fichiers ({}%)",

    tab_archive: "📦 Archive",
    tab_audio: "🎵 Audio",
    tab_doc: "📄 Doc",
    tab_image: "🖼️ Image",
    tab_scrapper: "🔍 Scrapper",
    tab_tag: "🏷️ Tag",
    tab_tools: "🛠 Outils",
    tab_video: "🎬 Vidéo",
    tab_settings: "⚙ Paramètres",

    format_label: "Format :",
    action_label: "Action :",
    angle_label: "Angle :",
    pages_label: "Pages :",
    pages_hint: "(ex: 1,3,5 ou vide = toutes)",
    save_format: "💾 Sauvegarder ce format",
    run_all: "🔥 EXÉCUTER TOUT",
    browse: "📂 Parcourir",
    clear_all: "🗑️ Tout effacer",
    drop_here: "📥 Glissez vos fichiers ici",

    compression_slider: "Compression (1=rapide, 9=qualité)",

    doc_convert: "Convertir",
    doc_pdf_compress: "PDF compresser",
    doc_pdf_crop: "PDF rogner",
    doc_pdf_delete_pages: "PDF supprimer pages",
    doc_pdf_merge: "PDF fusionner",
    doc_pdf_number_pages: "PDF numéroter pages",
    doc_pdf_organize: "PDF réorganiser pages",
    doc_pdf_protect: "PDF protéger",
    doc_pdf_repair: "PDF réparer",
    doc_pdf_rotate: "PDF rotation",
    doc_pdf_split: "PDF diviser",
    doc_pdf_unlock: "PDF déchiffrer",
    doc_pdf_watermark: "PDF filigrane",
    doc_split_hint1: "✂️ Divise chaque page du PDF en fichier séparé",
    doc_split_hint2: "💡 Crée un dossier _pages/ à côté du fichier source",
    doc_merge_hint1: "📎 Fusionne tous les fichiers chargés en un seul PDF",
    doc_merge_hint2: "💡 Le résultat sera merged_oxytools.pdf",
    doc_compress_hint: "🗜️ Réduit la taille du PDF en recompressant",
    doc_repair_hint1: "🔧 Tente de réparer un document corrompu",
    doc_repair_hint2: "Supprime les objets orphelins, recompresse, renumérate",
    doc_repair_hint3: "💡 Fonctionne sur tous les formats du module Doc",
    doc_watermark_hint1: "💧 Ajoute un filigrane texte diagonal",
    doc_watermark_hint2: "💡 Fonctionne sur tous les formats du module Doc",
    doc_margins: "Marges en % (0.0 – 100.0) :",
    doc_new_order: "🔀 Nouvel ordre des pages (ex: 3,1,2) :",
    doc_delete_pages: "🗑️ Pages à supprimer (ex: 2,4,6) :",
    doc_start: "Début :",
    doc_position: "Position :",
    doc_size: "Taille :",
    doc_owner_password: "Mot de passe propriétaire :",
    doc_user_password: "Mot de passe utilisateur :",
    doc_password: "Mot de passe :",
    doc_allow_print: "Autoriser impression",
    doc_allow_copy: "Autoriser copie",
    doc_text: "Texte :",
    doc_opacity: "Opacité :",

    img_convert: "Convertir",
    img_crop: "Rogner",
    img_resize: "Redimensionner",
    img_rotate: "Pivoter",
    img_quality_slider: "Qualité (1=rapide, 10=qualité)",
    img_resize_px: "Redimensionner par pixels :",
    img_width: "Largeur :",
    img_height: "Hauteur :",
    img_andor: "ET/OU",
    img_max_size: "Poids max (Ko) :",
    img_coordinates: "Coordonnées en % (0-100) :",

    audio_extract: "Extraire audio",
    audio_convert: "Convertir",
    audio_detect_codec: "🔍 Détecter codec",
    audio_vbr_slider: "VBR (1=rapide, 9=qualité)",
    audio_extract_hint1: "🎵 Extrait la piste audio d'une vidéo (copie directe, sans réencodage)",
    audio_extract_hint2: "💡 Le format de sortie est détecté automatiquement",

    video_stream_copy: "Copie flux",
    video_quality_slider: "Qualité (1=rapide, 8=qualité)",

    scrap_tmdb_key: "TMDB API Key :",
    scrap_fanart_key: "Fanart API Key :",
    scrap_save_keys: "💾 Sauvegarder les clés",
    scrap_movie: "🎬 Film",
    scrap_series: "📺 Série",
    scrap_choose: "Choisir",

    tag_mark_watched: "✅ Marquer VU",
    tag_inject_nfo: "📥 Injecter tags depuis NFO",
    tag_add_poster: "🖼️ Ajouter poster / fanart",
    tag_reset_tags: "🗑️ Reset Tags",
    tag_edit_title: "✏️ Modifier Titre",

    tab_rename: "✏️ Renommer",
    rename_find_replace: "🔍 Chercher & Remplacer",
    rename_find: "Chercher :",
    rename_replace_with: "Remplacer par :",
    rename_insert: "➕ Insérer",
    rename_text: "Texte :",
    rename_at_pos: "À la position :",
    rename_delete_range: "✂️ Supprimer plage",
    rename_enable: "Activer",
    rename_from: "Depuis :",
    rename_count: "Nombre :",
    rename_numbering: "🔢 Numérotation",
    rename_start: "Début :",
    rename_step: "Pas :",
    rename_padding: "Rembourrage :",
    rename_separator: "Séparateur :",
    rename_position: "Position :",
    rename_prefix: "Préfixe",
    rename_suffix: "Suffixe",
    rename_case: "🔤 Casse",
    rename_clean: "🧹 Nettoyer",
    rename_trim_spaces: "Supprimer espaces",
    rename_double_spaces: "Supprimer doubles espaces",
    rename_leading_dots: "Supprimer points initiaux",
    rename_strip_chars: "Supprimer caractères :",
    rename_extension: "📎 Extension",
    rename_new_ext: "Nouvelle ext :",
    rename_reset: "↺ Réinitialiser",
    rename_original: "Original",
    rename_new_name: "→ Nouveau nom",
    rename_apply: "🔥 Appliquer renommage",
    rename_done: "fichiers renommés",

    settings_heading: "Paramètres",
    settings_theme: "Thème :",
    settings_performance: "Performance",
    settings_max_jobs: "Jobs parallèles max :",
    settings_jobs_hint: "💡 Plus = plus rapide mais plus de charge CPU",
};

// ─── Helpers de formatage ───────────────────────────────────────────────────
pub fn fmt2(template: &str, a: &str, b: &str) -> String {
    let s = template.replacen("{}", a, 1);
    s.replacen("{}", b, 1)
}

pub fn fmt3(template: &str, a: &str, b: &str, c: &str) -> String {
    let s = template.replacen("{}", a, 1);
    let s = s.replacen("{}", b, 1);
    s.replacen("{}", c, 1)
}
